name: ProtectionPlugin
version: 1.0
api-version: 1.13
main: de.joeakeem.spigotmc.plugin.spaceadmin.protection.ProtectionPlugin

commands:
  claim:
    description: Claim a region (/claim start, /claim finish, /claim cancel)
  unclaim:
    description: Unclaim the region at your location
  listclaims:
    description: List all your claimed regions
  claimborder:
    description: Toggle particle border for your claimed regions
  adminclaims:
    description: Admin GUI to view and remove all claimed regions
  claimmanage:
    description: Manage your claim with a GUI
  spawnarea:
    description: Set or delete spawn protection areas (OP only)
